### ISSUE TITLE
Console.CancelKeyPress not work

### ISSUE THREAD

**Issue by szmcdull** [henon/pythonnet_netstandard#1]
### Environment

-   Pythonnet version: Python.Runtime.NETStandard 3.7.1
-   Python version: 3.7.4
-   Operating System: Windows 10 Version 10.0.18362.295

### Details

-   Describe what you were trying to get done.

```
Console.CancelKeyPress += OnCancelKeyPressed;
```
OnCancelKeyPressed() get called when Ctrl-C is pressed.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```
using (Py.GIL()) {...} or
Runtime.Initialize(true); or
PythonEngine.Initialize(false, true);
```
all of the above prevent Console.CancelKeyPress from working

**Comment by szmcdull** [comment]
i figure out that if I call PythonEngine.Initialize() first and then set Console.CancelKeyPress, it works. This is great!

**Comment by henon** [comment]
ok, cool. I was gonna suggest raising the issue on https://github.com/pythonnet/pythonnet because I really don't know why this is happening. Maybe Python overwrites the event handler at a low-level interface. 

Closing.
