### ISSUE TITLE
Cannot subscribe to any event: Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.

### ISSUE THREAD

**Issue by TheCollegedude** [henon/pythonnet_netstandard#10]
I have a C# application with embedding python for scripted plugins.
Subscribing to/Unsubscribing from any type of event (e.g. public event EventHandler TheEvent)
`TheEvent += System.EventHandler(lambda o,a: print(a))`
results in error
`Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.`
It is not related to the lambda, it won't work either with a function nor with omitting the explicit System.EventHandler.

This does not happen, when my C# DLL is loaded in python, then it works fine!

Does anyone have an idea? 
Thank you!

Latest stable (3.7.2) with python 3.7.7 and .NET Framework 4.8

**Comment by henon** [comment]
Please try if you have the same error when using vanilla pythonnet and .NET Framework. If so, their repo would be a better place to ask. Make sure to provide a small code snippet that allows them to reproduce the problem easily to increase your chance of getting it fixed.

**Comment by TheCollegedude** [comment]
Thank you very much! I have replaced the nuget package with pythonnet_py37_win and it works perfectly. 

Here is a minimalistic project
```
  namespace ConsoleApp1
  {
      class Test
      {
          public event EventHandler MyEvent;
      }
      class Program
      {
          static void Main(string[] args)
          {
              PythonEngine.PythonHome = @"C:\Users\User\Anaconda3";
              PythonEngine.Initialize();
              using var p = Py.CreateScope();
              p.Set("a", new Test());
              p.Exec("import System");

              // The line below throws System.MissingMethodException with Python.Runtime.Windows/NETStandard
              // But works perfectly with pythonnet_py37_win
              p.Exec("a.MyEvent += System.EventHandler(lambda o, e: print(e))");
          }
      }
  }
```

**Comment by henon** [comment]
I single stepped it. This error seems to happen in code emitted by the pythonnet runtime. I am sorry, but I am not able to fix it.  The original authors of pythonnet might be though. 

In any case, it has nothing to do with my fork, no need to bring it up when you raise the issue there.  Their code already has built in support for .NET Standard by way of the `NETSTANDARD` conditional compilation symbol. I only made some minor improvements in my fork.

**Comment by TheCollegedude** [comment]
@henon OK, Thank you!
