### ISSUE TITLE
which changeset is relative to pythonnet_netstandard_py37_win NUGET version?

### ISSUE THREAD

**Issue by huangyhg** [henon/pythonnet_netstandard#14]
### Environment

-   Pythonnet version:
-   Python version:
-   Operating System:

### Details

-   Describe what you were trying to get done.

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by henon** [comment]
I don't know what you mean. Can you clarify your question? Thanks

**Comment by huangyhg** [comment]
I hope to build pythonnet_netstandard_py37_win to get .pdb file(watch the varible values), which changeset or branch did build for Python.Runtime.NETStandard 3.7.1(used for numpy.bare)?

**Comment by huangyhg** [comment]
or would you like to share Python.Runtime.pdb (3.7.1) file?

**Comment by henon** [comment]
It ships version 2.5.1 of pythonnet. Just build the current source code of my fork in debug mode with the constants  `PYTHON3;PYTHON37;UCS2;NETSTANDARD;FINALIZER_CHECK;XPLAT` .
