### ISSUE TITLE
Does not work with net5.0

### ISSUE THREAD

**Issue by mnelsonwhite** [henon/pythonnet_netstandard#15]
Using `net5.0` console application

```
if (!PythonEngine.IsInitialized)
    PythonEngine.Initialize();

Py.Import("keras"); // throws here
```

throws an exception

```
System.IO.FileNotFoundException: {"Could not load file or assembly 'org, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.":"org, Culture=neutral, PublicKeyToken=null"}
```

Everything seems to work fine with earlier frameworks.

**Comment by henon** [comment]
I guess my fork should be updated against the upstream pythonnet repo. After all, all I added is a release bot capable of compiling all the nugets for the different python versions, platforms and frameworks. Problem is, that I am much too busy.
