### ISSUE TITLE
Calling python function from KERAS.NET doesn't return

### ISSUE THREAD

**Issue by patmach** [henon/pythonnet_netstandard#17]
### Environment

-   Pythonnet version: 2.5.1 
-   Python version: 3.8
-   Operating System: win10

### Details

I'm developing a card game that is played by a neural network. I'm using Keras.NET library and calling model.predict (model is an instance of Sequential class). 

This is the only part where python is called, when the game is played:
``` c#
public override List<float> GetResult(List<float> input)
{
    var NDArrayResult = model.Predict(new Numpy.NDarray<float>(input.ToArray()).reshape(1, inputCount, 1), verbose: 0);
    float[] result = NDArrayResult.GetData<float>();
    return result.ToList();
}
```

I have 2 different startup projects, one is ConsoleApp, where everything goes just fine. But if I play the game in my Windows Forms app, the first few (1,2,3,4,..) python calls are successful, but then it just doesn't return from calling the python function... Sometimes it stops in the ```Predict``` function, sometimes in ```reshape```.

**Does anyone know, what could be the problem? Or how to solve the problem so that the game can continue?**

I tried to call this part of code as a task and wait for period of time and then call the method again. It worked but occasionally caused the System.AccessViolationException...

**Comment by henon** [comment]
Check out my documentation on Numpy.NET under multi-threading, maybe you need to use the GIL: https://github.com/SciSharp/Numpy.NET#multi-threading-must-read

**Comment by patmach** [comment]
Thank you, it seems the problem is solved.
