### ISSUE TITLE
unity3d crashes on the second run

### ISSUE THREAD

**Issue by akaimody123** [henon/pythonnet_netstandard#18]
Hi, I'm using "Keras.NET" in Unity3d, which uses "pythonnet_standard_py38_win".  I'm facing the problem that it only allows me to run once in Unity and crashes on the second time. It seems to be an issue of an old version of "pythonnet" and they have addressed that in their new version by adding softshutdown feature. However, it seems this feature is not in "pythonnet_standard_py38_win", as when I try to do "PythonEngine.Initialize(softShutdown: true)"  it says "the best overload for initialize does not have a parameter named softShutDown". Could you please provide us with the folk of the new version of pythonnet? Thank you very much!

**Comment by henon** [comment]
I just generated nugets for pythonnet version 2.5.2. Don't know if the fix you need is in them already. If not let me know the exact pythonnet commit that introduces the new parameter.

**Comment by akaimody123** [comment]
Thank you very much @henon ! I just tested it but unfortunately that feature seems not in 2.5.2. I think the commits are here: https://github.com/pythonnet/pythonnet/pull/958, not sure if they have added this in their latest release.

**Comment by henon** [comment]
Looks like they haven't released anything for over a year despite many changes to master. I can't find any tags after 2.5.2. 
I wouldn't even know what number I should give it. Who knows, is it going to be 2.5.3 or 2.6.0 or 3.0.0? :(

Can you push on their repo for them to find a version number for the latest changes? If it isn't stable yet they can also label a pre-release or an alpha. I could then release nugets for that.
