### ISSUE TITLE
any chance for a pythonnet_netstandard_py310_{OS} nuget package?

### ISSUE THREAD

**Issue by dradoaica** [henon/pythonnet_netstandard#19]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.10
-   Operating System: Windows, Linux

### Details

-   Describe what you were trying to get done.

    need of a pythonnet_netstandard_py310_{OS} nuget package

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by henon** [comment]
I think it is not necessary for us to post nuget packages any more since the original pythonnet nuget is now compatible with all versions of .net and all platforms.
