### ISSUE TITLE
Linux - cannot load shared library "python36" and "kernel32.dll"

### ISSUE THREAD

**Issue by szmcdull** [henon/pythonnet_netstandard#2]
### Environment

-   Pythonnet version: Python.Runtime.NETStandard 3.6.1 from nuget
-   Python version: 3.6.8
-   Operating System: CentOS Linux release 7.6.1810 (Core)

### Details

-   Describe what you were trying to get done.

    initialize pythonnet

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```
PythonEngine.Initialize(true, false);
```

-   If there was a crash, please include the traceback here.

At first it could not find libpython36.so
```
System.DllNotFoundException: Unable to load shared library 'python36' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython36: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
```
then I did:
```
ln -s /usr/lib64/libpython3.6m.so.1.0 /usr/lib64/libpython36.so
```
and then it cannot find kernel32.dll now:
```
System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Python.Runtime.NativeMethods.LoadLibrary(String dllToLoad)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
```

my program is build using the following command:
```
dotnet publish --self-contained -c Release -r linux-x64
```

**Comment by szmcdull** [comment]
I read your blog and try to use Python.Included
```
            var installer = new Python.Included.Installer();
            await installer.SetupPython(force: false);
```
It works in Windows. But not in Linux either.
My projects use .net core 3.0, not mono. Will this be supported?

**Comment by henon** [comment]
if you are willing to work on it ;) ... seems like easy to solve for someone who has a linux box and wants it solved. I'll release a linux nuget if you manage to get it working and send a PR.

**Comment by henon** [comment]
> I read your blog and try to use Python.Included
> 
> ```
>             var installer = new Python.Included.Installer();
>             await installer.SetupPython(force: false);
> ```
> 
> It works in Windows. But not in Linux either.
> My projects use .net core 3.0, not mono. Will this be supported?

This is misplaced. it is not a pythonnet_netstandard problem, it is a Python.Included problem. Pythonnet_netstandard is available for linux: https://www.nuget.org/packages/Python.Runtime.Linux/
but Python.Included isn't yet

**Comment by szmcdull** [comment]
> 
> 
> if you are willing to work on it ;) ... seems like easy to solve for someone who has a linux box and wants it solved. I'll release a linux nuget if you manage to get it working and send a PR.

I wonder if we can put windows/linux/mac dists all in one nuget package. I'm looking into MS [doc](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders):
```
\runtimes
    \win10-arm
        \native
        \lib\uap10.0
    \win10-x86
        \native
        \lib\uap10.0
    \win10-x64
        \native
        \lib\uap10.0
```

**Comment by szmcdull** [comment]
I try to release a nuget package with the following folder structure:
```
└───runtime
    ├───linux-x64
    │   └───lib
    │       └───netstandard2.0
    ├───osx-x64
    │   └───lib
    │       └───netstandard2.0
    └───win-x64
        └───lib
            └───netstandard2.0
```
with no luck. Project consuming the package cannot reference the Python.Runtime.dll inside it. Seems the `runtime` folder is only for native libraries. Maybe consider building one Python.Runtime.dll for all platforms, removing the #ifs.

**Comment by szmcdull** [comment]
I confirm the `Python.Runtime.Linux` works under Linux without Mono. Now I can consume the nuget package using condition attributes:
```
    <PackageReference Include="Python.Runtime.Windows" Version="3.7.2" Condition="'$(RuntimeIdentifier)' != 'linux-x64' AND '$(RuntimeIdentifier)' != 'rhel.6-x64'"/>
    <PackageReference Include="Python.Runtime.Linux" Version="3.6.2" Condition="'$(RuntimeIdentifier)' == 'linux-x64' OR '$(RuntimeIdentifier)' == 'rhel.6-x64'" />
```
When I debug in Visual Studio, RuntimeIdentifier is empty ('$(RuntimeIdentifier)' == ''). When I publish the project to my server, I must specify the RuntimeIdentifier with the -r argument:
```
dotnet publish --self-contained -c Release -r linux-x64
```
Maybe you can make Python.Runtime.NETStandard conditionally depend on Python.Runtime.Windows/Linux/OSX? I haven't tried yet as I am happy with what I've tried by now.

**Comment by henon** [comment]
> Maybe you can make Python.Runtime.NETStandard conditionally depend on Python.Runtime.Windows/Linux/OSX? I haven't tried yet as I am happy with what I've tried by now.

That would be a nice solution if possible. Not sure how to get that working though.

**Comment by henon** [comment]
looks like you did it https://www.nuget.org/packages/Python.Runtime.AllPlatforms/3.7.2

**Comment by szmcdull** [comment]
> 
> 
> looks like you did it https://www.nuget.org/packages/Python.Runtime.AllPlatforms/3.7.2

That was only for testing. Not working yet.

**Comment by szmcdull** [comment]
OK. It should work now. https://www.nuget.org/packages/Python.Runtime.AllPlatforms/3.7.2.3

**Comment by henon** [comment]
Cool, how did you create that nuget? Could you send a pull request?

**Comment by szmcdull** [comment]
I just zip it manually

**Comment by szmcdull** [comment]
Final folder structure:
```
./
│   Python.Runtime.AllPlatforms.nupkg
│   Python.Runtime.AllPlatforms.nuspec
│   [Content_Types].xml
│
├───ref
│   └───netstandard2.0
│           Python.Runtime.dll
│
└───runtimes
    ├───linux-x64
    │   └───lib
    │       └───netstandard2.0
    │               Python.Runtime.dll
    │
    ├───osx-x64
    │   └───lib
    │       └───netstandard2.0
    │               Python.Runtime.dll
    │
    └───win-x64
        └───lib
            └───netstandard2.0
                    Python.Runtime.dll
```
The `runtimes` folder is used only in run-time and final publish. The `ref` folder is used in design-time so that the IDE and compiler would not complain about missing namespaces and classes.

**Comment by dasMulli** [comment]
If there is a build process that can create all these files (variants of Python.Runtime.dll), i could help you set up a build that works with `dotnet pack` - as long as one platform can build these versions.
Previously used a manually compiled version from the master branch but now that i move xplat & docker, this nuget packge is super helpful.

**Comment by henon** [comment]
great @dasMulli, I'd much appreciate if you would be able to extend my ReleaseBot [see source code](https://github.com/henon/pythonnet_netstandard/blob/master/ReleaseBot/Program.cs) to create such a nuget as @szmcdull created manually. That will make sure that such a nuget will be available for all future updates to the library. If you need my help I'll try to make some time.

**Comment by dasMulli** [comment]
Looks fine, i'll likely need to play with it for some time but it looks doable.
It should also be possible to merge mono and netstandard assemblies in one package with `lib\osx-x64\net4{forgot_which}\..` as well as netstandard.
If there is a canonical build slice that can be used as public API, the file in `\ref` could even be generated by roslyn through the `<ProduceReferenceAssembly>` property.
Upside: could be a single package for both .NET Framework (netfx on win, mono on others) and .NET Standard for each version combo.
Downside: Restoring RID-specific content for .NET Framework applications is a bit of a mess.. NuGet gets its knowledge about RIDs form a "RID graph" that is distriuted via NuGet - if the package references `Microsoft.NETCore.Platforms` it works because the graph is in there. Only the latest previews of NuGet already contain this graph with the tooling, but i'm not sure if this is exclusive to the `dotnet` CLI. Worst case: TFM-specific dependency on this package for net* only.

**Comment by henon** [comment]
@dasMulli I upgraded the release_bot to release pythonnet not only for netstandard2.0 but also for net40, all in one go. Also in order to easily rebase to newer pythonnet versions I completely cleaned up this repos commit history. 

if you still want to improve upon the release_bot you'd be very welcome to do so, as the number of packages that arise from all combinations of compilation targets is exploding.
