### ISSUE TITLE
Is osx-arm64 supported?

### ISSUE THREAD

**Issue by szmcdull** [henon/pythonnet_netstandard#20]
### Environment

-   Pythonnet version: 2.5.2.0
-   Python version: 3.8.13
-   Operating System: OSX 12.0.1
-   Nuget Package: pythonnet_netstandard_py39_osx

### Details

-   Could not load Python.Runtime.dll

System.BadImageException: Could not load file or assembly 'Python.Runtime, Version=2.5.2.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format

**Comment by henon** [comment]
Please use pythonnet directly. They support everything in their newest version now, including .net standard and .net core and all platforms.

**Comment by szmcdull** [comment]
But their API is not compatible :( And their new version is still in alpha stage

**Comment by henon** [comment]
That is too bad. 
As for my osx package, I don't own a mac, so I can't do any testing. You would have to find out with which flags the pythonnet code has to be compiled. You can look at my code which flags I am currently using for OSX. Someone told me that those worked before, maybe for older macs?
