### ISSUE TITLE
Python.NET 3.0 RCs

### ISSUE THREAD

**Issue by lostmsu** [henon/pythonnet_netstandard#21]
Hi!

Just wanted to invite you to test the upcoming Python.NET 3.0 release, and perhaps jump on potentially relevant discussion about NumPy interoperability: https://github.com/pythonnet/pythonnet/issues/1936

I am assuming this repo will be obsoleted by the release as 3.0 is .NET Standard 2.0 compatible, but NumPy and other bindings built on top of this package should be retested with https://www.nuget.org/packages/pythonnet/ 3.0.0-rc4 or later

**Comment by henon** [comment]
Yes you are right, this repo is obsolete now ;) 
Thank you for the heads up!
