### ISSUE TITLE
ConsoleApp.dll has exited with code 0

### ISSUE THREAD

**Issue by emilmuller** [henon/pythonnet_netstandard#3]
Can't make this work on Linux Mint 19 (Ubuntu 18.04).
Installed Python.Runtime.AllPlatforms 3.7.2.4.
It seems to crash on Py.GIL():

```
using (Py.GIL())
{
    dynamic np = Py.Import("numpy");
    Console.WriteLine(np.cos(np.pi * 2));

    dynamic sin = np.sin;
    Console.WriteLine(sin(5));

    double c = np.cos(5) + sin(5);
    Console.WriteLine(c);

    dynamic a = np.array(new List<float> { 1, 2, 3 });
    Console.WriteLine(a.dtype);

    dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
    Console.WriteLine(b.dtype);

    Console.WriteLine(a * b);
    Console.ReadKey();
}
```

There is no error message whatsoever:

```
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Reflection.Emit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '__CodeGenerator_Assembly'. 
Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[5538] ConsoleApp2.dll' has exited with code 0 (0x0).
```

Happens on the unforked version as well :)

Kind regards, Emil

**Comment by henon** [comment]
What are the compilation constants you are using to compile pythonnet for linux?

**Comment by emilmuller** [comment]
Didn't compile it :) Used Python.Runtime.AllPlatforms from nuget. Although it is worth mentioning that I did originally try the unforked pythonnet version which had the same problem. There, I compiled it with ReleaseMonoPy3 which had XPLAT;;PYTHON3;PYTHON37;UCS4;MONO_LINUX;PYTHON_WITH_PYMALLOC.
I also tried compiling and installing Python 3.7 without pymalloc (and also removing PYTHON_WITH_PYMALLOC).

It seems to find the shared object file just fine (no DllNotFoundException).

**Comment by emilmuller** [comment]
Upon further inspection, it seems to terminate on this line:

`fn = PyObject_GetAttrString(platformModule, "system");`

in runtime.cs in InitializePlatformData(). As I have no idea what I'm doing, I tried both UCS2 and UCS4, but same occurs.

I think it terminates because, on the line above, the following returns a null pointer:
`
IntPtr platformModule = PyImport_ImportModule("platform"); // Returns IntPtr.Zero`

Also tried setting PYTHONHOME:

`Environment.SetEnvironmentVariable("PYTHONHOME", "/usr/local/lib/python3.7");`

**Comment by emilmuller** [comment]
Once again, I have no idea what I'm doing :) However, I thought it might be a good idea to find out what sys.path evaluates to. So I injected this code into InitializePlatformData():
```

            IntPtr sysModule = PyImport_ImportModule("sys");
            var foo = PyObject_GetAttrString(sysModule, "path");
```

foo does indeed contain a valid pointer. I don't know how I can view it though.

**Comment by henon** [comment]
So the conclusion is PyImport_ImportModule is unable to find the Python libraries? If so, maybe try this: https://github.com/SciSharp/Keras.NET/issues/38#issuecomment-538713866

**Comment by emilmuller** [comment]
`Console.WriteLine(PythonEngine.PythonHome)`

prints an empty line, even though I set the environment variable.

So I tried this after looking at https://github.com/pythonnet/pythonnet/issues/259#issuecomment-245415530:

```
Environment.SetEnvironmentVariable("PATH", path, EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PYTHONHOME", @"/usr/local/bin/python3.7", EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("PYTHONPATH ", @"/usr/local/lib/python3.7", EnvironmentVariableTarget.Process);
```

But still:

`Console.WriteLine(PythonEngine.PythonHome) // Empty`

**Comment by henon** [comment]
I am just shooting in the dark, but have you tried to set `PythonEngine.PythonHome` directly?

**Comment by emilmuller** [comment]
Yes, I did try it before initializing, but it didn't have any effect

**Comment by emilmuller** [comment]
Apparently:

```
            PythonEngine.PythonHome = @"/usr/local/bin/python3.7";
            PythonEngine.PythonPath = @"/usr/local/lib/python3.7";
```

Had an effect, as it caused a fatal crash. Changing to UCS4 made it not fatally crash, but 

`fn = PyObject_GetAttrString(platformModule, "system");`

is still NULL

I thought Python was UTF-8, but I guess it uses sizeof(wchar_t) == 4.

**Comment by emilmuller** [comment]
Interestingly, PyErr_Fetch gives me:

`ModuleNotFoundError : No module named '_posixsubprocess'`

**Comment by henon** [comment]
OK, you are now way out of my depth of knowledge with this. I suggest taking that to the pythonnet and/or Python communities. Good luck and let me know when you got it resolved.

**Comment by emilmuller** [comment]
Thanks for the help :) I reported it here: https://github.com/pythonnet/pythonnet/issues/967. Will let you know if it gets resolved.

**Comment by henon** [comment]
Here is something else you can try:

PythonEngine.Initialize(); 

at the beginning, after setting the paths

**Comment by emilmuller** [comment]
Did it already. Not working :)

man. 7. okt. 2019, 15:42 skrev Meinrad Recheis <notifications@github.com>:
