### ISSUE TITLE
Py.GIL() hangs

### ISSUE THREAD

**Issue by oujunke** [henon/pythonnet_netstandard#5]
After calling Py.GIL() in a child thread and releasing it, if the thread has not completed execution, it will cause the next Py.GIL() to hang
System environment:
1.Win10
2.Python3.7 X64
3.Python.Runtime.NETStandard3.7.1
4..net framework 4.8
Code:
![image](https://user-images.githubusercontent.com/26790160/71329566-a051eb00-2561-11ea-9506-6008a098efb2.png)
Result:
![image](https://user-images.githubusercontent.com/26790160/71329574-afd13400-2561-11ea-8cd6-136d76878ff3.png)
Suspended location:
![image](https://user-images.githubusercontent.com/26790160/71300771-f7758580-23d2-11ea-9334-9b683eb234f7.png)

**Comment by henon** [comment]
Check this out: https://github.com/SciSharp/Numpy.NET#multi-threading

**Comment by oujunke** [comment]
thank you
