### ISSUE TITLE
Binding failure Winforms framwork 4.7 ,not core

### ISSUE THREAD

**Issue by kiranmaya** [henon/pythonnet_netstandard#6]
Everything Runs fine ,in an empty winform with a single button  project (Core and .netFramework), but when i integrated into my large Actual project (.netframework ),it throws binding errors.

"Managed Debugging Assistant 'BindingFailure' : 'The assembly with display name 'org' failed to load in the 'Load' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileNotFoundException: Could not load file or assembly 'org' or one of its dependencies. The system cannot find the file specified.'
"
Thanks 
Kiran

**Comment by henon** [comment]
You can add a dependency handler callback to the app domain and set a breakpoint there to get more information about the dependency that failed to load
