### ISSUE TITLE
EEFileLoadException - dependency not present?

### ISSUE THREAD

**Issue by simonbuehler** [henon/pythonnet_netstandard#7]
### Environment

-   Pythonnet version: 3.7.1
-   Python version: 3.7.6
-   Operating System: win10

### Details

-   Describe what you were trying to get done.
Hi,
trying to run keras.net  but the model.load() fails with a EEFileLoadException , so thats often a missing dep. i checked dependencies (see screenshot) and there are some python3.7 errors although its installed, also all nuget packages , any idea what am i missing here?

![grafik](https://user-images.githubusercontent.com/78061/73265651-aaf14700-41d5-11ea-9ea9-47889edf1cd9.png)

**Comment by henon** [comment]
I don't have in-depth Keras knowledge. Can you also post this issue on Keras.NET?

**Comment by simonbuehler** [comment]
I will do that, but the dependency walker shows a missing dep in pythonnet DLL, therefore I thought this would be the right place

**Comment by henon** [comment]
hmm, not sure about that. Pythonnet has been stable for a long time. I only made it compile for .NETStandard. Is there no way to find out which file failed to load?

**Comment by simonbuehler** [comment]
Hi, maybe https://github.com/pythonnet/pythonnet/issues/703 is related, does your code implement the changes merged there?

**Comment by henon** [comment]
yeah, pretty sure. I forked off pythonnet long after that.

**Comment by simonbuehler** [comment]
closing as it actually runs after a minute or so in debug mode, faster in release mode;
when i find something useful i will reopen
