### ISSUE TITLE
Xamarin - DllImport unable to load library

### ISSUE THREAD

**Issue by legyas** [henon/pythonnet_netstandard#8]
### Environment

-   Pythonnet version: 3.7.1
-   Python version:3.7
-   Operating System: Xamarin.Forms(.NET standard 2.0)

### Details

-   I'm trying to use this library in my xamarin App to run some python code, but when I call using(Py.GIL()){}, I get the error message below. Can this be fixed or am I wrong and to begin with the Library can't be used on xamarin? 

    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

``using (Py.GIL())
            {
                
            }
```


```DllImport unable to load library 'dlopen failed: library "libpython37" not found'.
**System.DllNotFoundException:** 'python37 assembly:<unknown assembly> type:<unknown type> member:(null)'
```

**Comment by henon** [comment]
Sorry, I can't help with this issue

**Comment by legyas** [comment]
why not? would you mind elaborating?

**Comment by henon** [comment]
Here is my guess. Probably you need to compile pythonnet with the correct compile time constants for your platform, I can't even say for sure which are required. I didn't write the library, I forked it. All I did was make pythonnet work for .NETStandard which was a minor change really.
