### ISSUE TITLE
How do i pass Bytes like object to the python library

### ISSUE THREAD

**Issue by aaronavi** [henon/pythonnet_netstandard#9]
### Environment

-   Pythonnet version:2.4
-   Python version:3.7
-   Operating System:win 10

### Details

-   I am trying to to run the command pickle.loads, it requires paramter a Bytes like object which contains the pickled data, i can't find anything that works in the API, can you assist?
Thanks

**Comment by henon** [comment]
Please give me a simple test script that I can use to reproduce your use-case.

**Comment by aaronavi** [comment]
Hi
Thank you for your response:
Here is a sample code:
 
```c#
public PyDict PickleLoads(byte[] PickleData)
{
            try
            {
                PyDict dDict = new PyDict();

                dDict["1"] = "2".ToPython();
                dynamic pickle = Import("pickle");
                dynamic resDump = pickle.dumps(dDict);
                
                // here everything works fine
               // How do i convert the byte[] PickleData, which contains the same data as resDump,
               //  to python object.
                dynamic resload = pickle.loads(resDump);           
            }
            catch (Exception ex)
            {
            }
            return null;
 }
```

**Comment by henon** [comment]
can you also give me a corresponding python script so I can compare results? thanks

edit: I got it.

```python
>>> b=pickle.dumps({"1":"2"})
>>> b
b'\x80\x03}q\x00X\x01\x00\x00\x001q\x01X\x01\x00\x00\x002q\x02s.'
>>> pickle.loads(b);
{'1': '2'}
>>>
```

**Comment by henon** [comment]
Wouldn't it just be `Encoding.ASCII.GetString(PickleData)` and pass that into `pickle.loads(...)`?

**Comment by aaronavi** [comment]
Hi
I tried and i am getting the following exception:
TypeError : a bytes-like object is required, not 'str'

StackTrace
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw) in C:\Code\EPMD\Kodex\Applications\Kodex.Core\PythonInterop\Python.Net.Runtime\pyobject.cs:line 709
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw) in C:\Code\EPMD\Kodex\Applications\Kodex.Core\PythonInterop\Python.Net.Runtime\pyobject.cs:line 773
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) in C:\Code\EPMD\Kodex\Applications\Kodex.Core\PythonInterop\Python.Net.Runtime\pyobject.cs:line 1068
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at PythonInterop.PythonInteropService.PickleLoads(Byte[] PickleData) in C:\Code\EPMD\Kodex\Applications\Kodex.Core\PythonInterop\PythonInteropLibrary\PythonInteropService.cs:line 160

**Comment by henon** [comment]
I don't yet know how to do it directly, but there is a workaround:

```c#
                var bytes=new byte[] {0x80, 0x03, (byte) '}', (byte) 'q'};
                var bytes_base64 = System.Convert.ToBase64String(bytes);
                dynamic base64 = Py.Import("base64");
                var bytes_object=base64.b64decode(bytes_base64);
                Console.WriteLine(bytes_object.ToString());
```

**Comment by henon** [comment]
OK, here is a better way:
```c#
                var bytearray = new byte[] { 0x80, 0x03, (byte)'}', (byte)'q' };
                PyObject builtins = Py.Import("builtins");
                PyObject bytes = builtins.GetAttr("bytes");
                var bytes_object=bytes.Invoke(bytearray.ToPython());
                Console.WriteLine(bytes_object.ToString());
```

**Comment by aaronavi** [comment]
Hi
Thanks for the response, this gives the pkl string, but i suspect it is in unicode format, when i try to unpickle it, i get:

"UnicodeDecodeError : 'ascii' codec can't decode byte 0x9d in position 0: ordinal not in range(128)"

in python it is possible to

pickle.loads(bytes_object, encoding="unicode")

is there anyway to resolve this issue, either by getting the "bytes_object" as ASCII, or call the pickle.loads with the encoding parameter

thanks

**Comment by aaronavi** [comment]
Hi
There is a correction to the python code which pickle.loads the data, it is required to use:

pickle.loads(myArr, encoding='latin1')

the encoding should be latin1, the pkl contains numpy object

thanks

**Comment by aaronavi** [comment]
OK, i think i got it, here is the solution, and it also works, thank you for your assistance, i really appreciate it.
try
            {
                
                PyObject builtins = Py.Import("builtins");
                PyObject bytes = builtins.GetAttr("bytes");
                var bytes_object = bytes.Invoke(PickleData.ToPython());

                
                dynamic pickle = Import("pickle");

                var res = pickle.loads(bytes_object, Py.kw("encoding", "latin1"));
                retDict = new PyDict(res);
                //string pathToFile = @"c:\temp\tempCalibration.pkl";
                //File.WriteAllBytes(pathToFile, PickleData);
                //retDict = PickleLoad(pathToFile);

            }
            catch (Exception ex)
            {
            }
